version: '3.4'

services:
  yakshop.mvc:
    image: vvellokkandi/yakshop.mvc:first
    expose:
      - "80"
    ports:
      - "5000:80"
    hostname: yakshop.mvc
    environment:
      - "ASPNETCORE_ENVIRONMENT=Container"
    depends_on:
      - yakshop.api
    networks:
        yak_network:
            ipv4_address: 192.168.112.10

  yakshop.api:
    image: vvellokkandi/yakshop.api:first
    expose:
      - "80"
    ports:
      - "8000:80"
    environment:
      - "Endpoints:Backend=http://yakshop.api"
      - "ASPNETCORE_ENVIRONMENT=Container"
    networks:
        yak_network:
            ipv4_address: 192.168.112.11

networks:
    yak_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.112.0/24
